src/Pizza.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pizza.Core.Services;
using Pizza.Data.Data;
using Pizza.Web.ViewModels;

namespace Pizza.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly ApplicationDbContext _dbContext;

        public CartController(ICartService cart, ApplicationDbContext context)
        {
            _cartService = cart;
            _dbContext = context;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetItems(HttpContext.Session);


            decimal sum = 0;
            if (cart != null)
            {
               sum = _cartService.GetTotalPrice(HttpContext.Session);
            }

            return View(new CartViewModel{
                Sum = sum,
                Cart = cart
            });
        }

        public async Task<IActionResult> Add(int id)
        {
            var pizza = await _dbContext.Pizzas.FirstOrDefaultAsync(p => p.Id == id);

            if (pizza == null)
            {
                return NotFound();
            }

            _cartService.AddToCart(pizza,HttpContext.Session);

            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> Remove(int id)
        {
            var pizza = await _dbContext.Pizzas.FirstOrDefaultAsync(p => p.Id == id);

            if(pizza == null)
            {
                return NotFound();
            }
            _cartService.Remove(pizza, HttpContext.Session);

            return RedirectToAction("Index");
        }

    }
}

src/Pizza.Web/Controllers/PizzasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pizza.Data.Data;
using PizzaShop.ViewModels;



namespace Pizza.Web.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class PizzasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PizzasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pizzas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pizzas.ToListAsync());
        }

        // GET: Pizzas/Details/5
        public async Task<IActionResult> Details(int? id) 
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizzas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // GET: Pizzas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pizzas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PizzaViewModel pizzaVm)
        {
            var pizza = new global::Pizza.Core.Entities.Pizza
            {
                Name = pizzaVm.Name, Diameter = pizzaVm.Diameter, Price = pizzaVm.Price,
                Weight = pizzaVm.Weight, Recipe = pizzaVm.Recipe
            };
            
            if (ModelState.IsValid && pizzaVm.Image != null)
            {
                byte[] imageBytes;
                using (var binaryReader = new BinaryReader(pizzaVm.Image.OpenReadStream()))
                {
                    imageBytes = binaryReader.ReadBytes((int) pizzaVm.Image.Length);
                }

                pizza.Image = imageBytes;

                _context.Add(pizza);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pizza);
        }

        // GET: Pizzas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizzas.FindAsync(id);
            if (pizza == null)
            {
                return NotFound();
            }
            return View(pizza);
        }

        // POST: Pizzas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Weight,diameter,Price,Recipe,Image")] global::Pizza.Core.Entities.Pizza pizza)
        {
            if (id != pizza.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pizza);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PizzaExists(pizza.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pizza);
        }

        // GET: Pizzas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizzas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // POST: Pizzas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pizza = await _context.Pizzas.FindAsync(id);
            _context.Pizzas.Remove(pizza);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PizzaExists(int id)
        {
            return _context.Pizzas.Any(e => e.Id == id);
        }
    }
}

src/Pizza.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Pizza.Web</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Pizza.Web.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" type="text/css" href="~/css/main.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/normalize.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/site.css"/>

</head>
<body>
<header>
    <nav class="navbar">  
             <div class="navbar_start">               
                    <ul class="navbar-nav">
                      <li class="nav-item">
                          <a class="nav-title" asp-area="" asp-controller="Home" asp-action="Index">Pizza.Web</a>
                      </li>
                     <li class="nav-item" asp>
                         <a class="nav-link" asp-area="" asp-controller="Pizzas" asp-action="Index">Admin</a>
                     </li>    
                    
                     <li class="nav-item">
                         <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                     </li> 
                 </ul>
         </div>
         <div class="navbar_end">
             <partial name="_LoginPartial"/>
         </div>
                      
    </nav>
</header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    


<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Pizza.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>